### ISSUE TITLE
[Bug]: NullPointerException when starting game (RTTexture.createGraphics)

### ISSUE THREAD

**Issue by sevarac** [jvondermarck/dinosaur-exploder#50]
### 👉 Please confirm the following

- [X] I agree to follow the [Code of Conduct](https://github.com/dylan-power/dinosaur-exploder/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I checked the [current issues](https://github.com/dylan-power/dinosaur-exploder/issues) for duplicate bugs.

### ❌ Current Behavior

When I run game from IDE (NetBEans) I get the exception:
java.lang.NullPointerException: Cannot invoke "com.sun.prism.RTTexture.createGraphics()" because "<local9>" is null
	at com.sun.javafx.sg.prism.NGCanvas$RenderBuf.validate(NGCanvas.java:214)
	at com.sun.javafx.sg.prism.NGCanvas.initCanvas(NGCanvas.java:644)
	at com.sun.javafx.sg.prism.NGCanvas.renderContent(NGCanvas.java:607)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at com.sun.javafx.tk.quantum.ViewPainter.doPaint(ViewPainter.java:480)
	at com.sun.javafx.tk.quantum.ViewPainter.paintImpl(ViewPainter.java:329)
	at com.sun.javafx.tk.quantum.PresentingPainter.run(PresentingPainter.java:92)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:126)
	at java.base/java.lang.Thread.run(Thread.java:833)

### ✅ Expected Behavior

Expecting to start game without exception

### 🚩 Steps To Reproduce

Just build and run game from NetBeans IDE
Screen resolution: 3840x2160

### 💻 Environment

```markdown
- OS:Windows 11
- JDK Java: 17.0.1
- Game version: 1.0-SNAPSHOT
```

**Comment by jvondermarck** [comment]
Hi @sevarac , it sounds like you're likely running out of VRAM. Do you have the possibility to downscale your resolution to 1080p to make it work ?

**Comment by sevarac** [comment]
Yes, it worked thanks!

**Comment by jvondermarck** [comment]
@sevarac Awesome!! Can you just say how did you do to downscale your screen (it can be great to explain for others people)?
And you were playing in a 4K screen?

**Comment by jvondermarck** [comment]
Answer from the author of FXGL --> https://github.com/AlmasB/FXGL/discussions/1163#discussioncomment-2485211
On StackOverflow : https://stackoverflow.com/questions/65565209/nullpointers-in-javafx-when-using-a-large-canvas

**Comment by sevarac** [comment]
> @sevarac Awesome!! Can you just say how did you do to downscale your screen (it can be great to explain for others people)? And you were playing in a 4K screen?

I've just changed screen resolution to 1280x1024
